config/routes.rb
Scrabble::Application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"

  get "log_in" => "sessions#new", :as => "log_in"

  get "sign_up" => "players#new", :as => "sign_up"

  root :to => "players#new"

  controller :api, defaults: {format:'json'} do
    get 'api/ranking' =>'api#ranking'
    get 'api/check_word/:word' => 'api#check_word'
    get 'api/compare' => 'api#compare'
  end

  resources :states

  resources :games
  put 'games/end/:id' => 'games#end' , as: 'end_game'

  resources :players do
    collection do
      get :ranking
    end    
  end

  resources :moves

  resources :sessions

end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :game_id, :user_id, :user_state, :turn, :player_state
  belongs_to :player
  belongs_to :game
  before_create :init

  include GamesHelper

  def init
     self.random_letters()
  end
  def random_letters()
    self.l1 = State.letter_distribution
    self.l2 = State.letter_distribution
    self.l3 = State.letter_distribution
    self.l4 = State.letter_distribution
    self.l5 = State.letter_distribution
    self.l6 = State.letter_distribution
    self.l7 = State.letter_distribution
  end
  def random_letter(i)
    if i==1
      self.l1 = State.letter_distribution
    elsif i==2
      self.l2 = State.letter_distribution
    elsif i==3
      self.l3 = State.letter_distribution
    elsif i==4
      self.l4 = State.letter_distribution
    elsif i==5
      self.l5 = State.letter_distribution
    elsif i==6
      self.l6 = State.letter_distribution
    elsif i==7
      self.l7 = State.letter_distribution
    end
  end
  def self.letter_distribution
    i = rand(1..100)
    if i<=9
      1
    elsif i<=11
      2
    elsif i<=13
      3
    elsif i<=17
      4
    elsif i<=29
      5
    elsif i<=31
      6
    elsif i<=34
      7
    elsif i<=36
      8
    elsif i<=45
      9
    elsif i<=46
      10
    elsif i<=47
      11
    elsif i<=51
      12
    elsif i<=53
      13
    elsif i<=59
      14
    elsif i<=67
      15
    elsif i<=69
      16
    elsif i<=70
      17
    elsif i<=76
      18
    elsif i<=80
      19
    elsif i<=88
      20
    elsif i<=92
      21
    elsif i<=94
      22
    elsif i<=96
      23
    elsif i<=97
      24
    elsif i<=99
      25
    else
      26
    end
  end
  def get_state_letter(i)
    if (i==1)
      return self.l1
    elsif(i==2)
      return self.l2
    elsif(i==3)
      return self.l3
    elsif(i==4)
      return self.l4
    elsif(i==5)
      return self.l5
    elsif(i==6)
      return self.l6
    else
      return self.l7
    end
  end
  def get_state_letters
    [[get_letter_from_number(self.l1.to_i),points_for_letter(get_letter_from_number(self.l1.to_i))],
     [get_letter_from_number(self.l2.to_i),points_for_letter(get_letter_from_number(self.l2.to_i))],
     [get_letter_from_number(self.l3.to_i),points_for_letter(get_letter_from_number(self.l3.to_i))],
     [get_letter_from_number(self.l4.to_i),points_for_letter(get_letter_from_number(self.l4.to_i))],
     [get_letter_from_number(self.l5.to_i),points_for_letter(get_letter_from_number(self.l5.to_i))],
     [get_letter_from_number(self.l6.to_i),points_for_letter(get_letter_from_number(self.l6.to_i))],
     [get_letter_from_number(self.l7.to_i),points_for_letter(get_letter_from_number(self.l7.to_i))]]
  end
  def replace_used_letters(moves)
    notUsed = Array.new(7) { true}
    moves.each do |move|
      if move.letter==get_letter_from_number(self.l1.to_i)  && notUsed[0]
        notUsed[0]= false
        self.random_letter(1)
      elsif move.letter==get_letter_from_number(self.l2.to_i) && notUsed[1]
        self.random_letter(2)
        notUsed[1]= false
      elsif move.letter==get_letter_from_number(self.l3.to_i) && notUsed[2]
        self.random_letter(3)
        notUsed[2]= false
      elsif move.letter==get_letter_from_number(self.l4.to_i) && notUsed[3]
        self.random_letter(4)
        notUsed[3]= false
      elsif move.letter==get_letter_from_number(self.l5.to_i) && notUsed[4]
        self.random_letter(5)
        notUsed[4]= false
      elsif move.letter==get_letter_from_number(self.l6.to_i) && notUsed[5]
        self.random_letter(6)
        notUsed[5]= false
      elsif move.letter==get_letter_from_number(self.l7.to_i) && notUsed[6]
        self.random_letter(7)
        notUsed[6]= false
      end
    end

  end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  # GET /states
  # GET /states.json
  def index
    @states = State.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @states }
    end
  end

  # GET /states/1
  # GET /states/1.json
  def show
    @state = State.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @state }
    end
  end

  # GET /states/new
  # GET /states/new.json
  def new
    @state = State.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @state }
    end
  end

  # GET /states/1/edit
  def edit
    @state = State.find(params[:id])
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(params[:state])

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render json: @state, status: :created, location: @state }
      else
        format.html { render action: "new" }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /states/1
  # PUT /states/1.json
  def update
    @state = State.find(params[:id])

    respond_to do |format|
      if @state.update_attributes(params[:state])
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state = State.find(params[:id])
    @state.destroy

    respond_to do |format|
      format.html { redirect_to states_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_form.html.erb
<%= form_for(@state) do |f| %>
  <% if @state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% @state.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :game_id %><br />
    <%= f.text_field :game_id %>
  </div>
  <div class="field">
    <%= f.label :user_state %><br />
    <%= f.text_field :user_state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/states/edit.html.erb
<h1>Editing state</h1>

<%= render 'form' %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<h1>Listing states</h1>

<table>
  <tr>
    <th>User</th>
    <th>Game</th>
    <th>User state</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @states.each do |state| %>
  <tr>
    <td><%= state.user_id %></td>
    <td><%= state.game_id %></td>
    <td><%= state.user_state %></td>
    <td><%= link_to 'Show', state %></td>
    <td><%= link_to 'Edit', edit_state_path(state) %></td>
    <td><%= link_to 'Destroy', state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New State', new_state_path %>

app/views/states/new.html.erb
<h1>New state</h1>

<%= render 'form' %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @state.user_id %>
</p>

<p>
  <b>Game:</b>
  <%= @state.game_id %>
</p>

<p>
  <b>User state:</b>
  <%= @state.user_state %>
</p>


<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>