config/routes.rb
Scrabble::Application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"

  get "log_in" => "sessions#new", :as => "log_in"

  get "sign_up" => "players#new", :as => "sign_up"

  root :to => "players#new"

  controller :api, defaults: {format:'json'} do
    get 'api/ranking' =>'api#ranking'
    get 'api/check_word/:word' => 'api#check_word'
    get 'api/compare' => 'api#compare'
  end

  resources :states

  resources :games
  put 'games/end/:id' => 'games#end' , as: 'end_game'

  resources :players do
    collection do
      get :ranking
    end    
  end

  resources :moves

  resources :sessions

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :states
  has_many :players, :through => :states
  has_many :moves , :order=> 'move_number DESC'
  attr_accessible :language_id, :buildBoard, :score

  include GamesHelper

  def build_board
    m = Array.new(15) {Array.new(15) {[nil, false, false,0]}}
    moves = self.moves
    moves.each do |x|
      pos_x = x.coordinate.split(",")[0].to_i
      pos_y = x.coordinate.split(",")[1].to_i
      m[pos_x][pos_y][0] = x.letter
      m[pos_x][pos_y][3] = points_for_letter(x.letter)
    end
    return m
  end
  def build_board_for_ajax
    m = Array.new(15) {Array.new(15) {[nil,0]}}
    moves = self.moves
    moves.each do |x|
      pos_x = x.coordinate.split(",")[0].to_i
      pos_y = x.coordinate.split(",")[1].to_i
      m[pos_x][pos_y][0] = x.letter
      m[pos_x][pos_y][1] = points_for_letter(x.letter)
    end
    m
  end
  def next_turn
     last_move = self.moves.first
     return 1 if last_move.nil?

     last_player_turn = last_move.player.states.where(game_id: self).first.turn


     (last_player_turn.to_i()) % (self.states.count) +1
  end
  def check_if_players_turn(player)

    last_move = self.moves.first
    if last_move
      last_player = last_move.player
      last_player_turn = last_player.states.where(:game_id => self).first.turn if last_player
    end


    states = State.where(:game_id => self)

    next_turn = (last_player_turn.to_i()) % (states.count) +1

    player_state = player.states.where(:game_id => self).last

    player_state.turn == next_turn
  end
  def generate_moves(params)
    @last_move = Move.where(:game_id =>self).maximum('move_number')
    moves=[]
    unless params[:tile_1].empty?
      m= Move.new()
      m.coordinate="#{params[:tile_1_x]},#{params[:tile_1_y]}"
      m.letter = params[:tile_1][-1, 1]
      @last_move.nil? ? m.move_number = 1 : m.move_number = @last_move.to_int + 1
      moves.push(m)
    end
    unless params[:tile_2].empty?
      m= Move.new()
      m.coordinate="#{params[:tile_2_x]},#{params[:tile_2_y]}"
      m.letter = params[:tile_2][-1, 1]
      @last_move.nil? ? m.move_number = 1 : m.move_number = @last_move.to_int + 1
      moves.push(m)
    end
    unless params[:tile_3].empty?
      m= Move.new()
      m.coordinate="#{params[:tile_3_x]},#{params[:tile_3_y]}"
      m.letter = params[:tile_3][-1, 1]
      @last_move.nil? ? m.move_number = 1 : m.move_number = @last_move.to_int + 1
      moves.push(m)
    end
    unless params[:tile_4].empty?
      m= Move.new()
      m.coordinate="#{params[:tile_4_x]},#{params[:tile_4_y]}"
      m.letter = params[:tile_4][-1, 1]
      @last_move.nil? ? m.move_number = 1 : m.move_number = @last_move.to_int + 1
      moves.push(m)
    end
    unless params[:tile_5].empty?
      m= Move.new()
      m.coordinate="#{params[:tile_5_x]},#{params[:tile_5_y]}"
      m.letter = params[:tile_5][-1, 1]
      @last_move.nil? ? m.move_number = 1 : m.move_number = @last_move.to_int + 1
      moves.push(m)
    end
    unless params[:tile_6].empty?
      m= Move.new()
      m.coordinate="#{params[:tile_6_x]},#{params[:tile_6_y]}"
      m.letter = params[:tile_6][-1, 1]
      @last_move.nil? ? m.move_number = 1 : m.move_number = @last_move.to_int + 1
      moves.push(m)
    end
    unless params[:tile_7].empty?
      m= Move.new()
      m.player_id = @player.id;
      m.coordinate="#{params[:tile_7_x]},#{params[:tile_7_y]}"
      m.letter = params[:tile_7][-1, 1]
      @last_move.nil? ? m.move_number = 1 : m.move_number = @last_move.to_int + 1
      moves.push(m)
    end
    moves
  end
  def submit_moves(params, player)

    return false unless self.check_if_players_turn player

    player_state = player.states.where(:game_id => self).last
    moves = self.generate_moves(params)
    m = self.build_board()
    ok_move = false
    words_created=nil


    if move_accepted(m, moves)
      words_created = validate_words(m)
      ok_move = save_move (words_created)
    end

    return false unless ok_move

    total_new_score = 0
    words_created.each do |word|
      total_new_score += word[1]
    end
    state = player_state
    play_score = total_new_score - self.score
    state.score += play_score
    state.replace_used_letters(moves)
    state.save!
    self.update_attributes(score: total_new_score)
    #self.score = total_new_score
    moves.each do |s|
      self.moves<<s
      player.moves<<s
    end
    self.touch
    player.save

  end
  def surrender (player)

    state = player.states.where(:game_id => self).last
    state.update_attributes(player_state:'inactive')
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  include GamesHelper
  # GET /games
  # GET /games.json
  def index
    @games = Game.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])
    states_game = @game.states
    @game_status = []
    @states=@game.states
    states_game.each do |s|
      state_player = State.find(s)
      #games_status recibe la tripla nome jugador, turno y score
      @game_status.push([Player.find(state_player.player_id).name, state_player.turn, state_player.score,state_player.player_id])
    end

    @player = current_player
    @player_state = @player.states.where(:game_id => @game).last

    @next_turn = @game.next_turn
    @playable= @game.check_if_players_turn(@player)

    respond_to do |format|
      format.html # show.html.erb
      format.js do
        if params[:updated_at].to_i  < @game.updated_at.to_i
          render 'show'
        else
          render js: {}
        end
      end
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new
    @player = current_player

    @player = Player.new if !current_player



    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json

  def create

    @game = Game.create()

    @player = current_player
    @player2 = Player.find_by_mail(params[:user1])
    #@player2 = Player.create(mail: params[:user1][:invited_email] )  if (!@player2 && !params[:user1][:invited_email].empty?)

    @player3 = Player.find_by_mail(params[:user2])
    #@player3 = Player.create(mail: params[:user2][:invited_email] ) if (!@player3 && !params[:user2][:invited_email].empty?)

    @player4 = Player.find_by_mail(params[:user3])
    #@player4 = Player.create(mail: params[:user3][:invited_email] )  if (!@player4 && !params[:user3][:invited_email].empty?)

    turn = 1
    if @player
      @state = @player.states.create(:game_id => @game, :turn => turn, :player_state => 'active')
      turn= turn+1
    end
    if @player2
      @state2 = @player2.states.create(:game_id => @game, :turn => turn, :player_state => 'active')
      turn= turn+1
    end
    if @player3 && @player3 != @player2
      @state3 = @player3.states.create(:game_id => @game, :turn => turn, :player_state => 'active')
      turn= turn+1
    end
    if @player4 && @player4 != @player2 && @player3 != @player4
      @state4 = @player4.states.create(:game_id => @game, :turn => turn, :player_state => 'active')
      turn= turn+1
    end

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end



  # PUT /games/1
  # PUT /games/1.json
  def update

    @game = Game.find(params[:id])
    @player = current_player
    @player_state = @player.states.where(:game_id => @game).last
    @states = @game.states;
    success = @game.submit_moves params,@player
    #no supe como actualizarlo
    @game = Game.find(params[:id])
    respond_to do |format|
      if success
        format.html { redirect_to @game, notice: 'Accepted move.' }
        format.js
        format.json { head :no_content }
      else
        format.html { redirect_to @game, notice: 'Invalid move.' }
        format.js
      end
    end
  end
  def end

    @game = Game.find(params[:id])
    @player = current_player
    @player_state = @player.states.where(:game_id => @game).last

    success = @game.surrender @player

    #no supe como actualizarlo
    respond_to do |format|
      if success
        format.html { redirect_to @player, notice: 'Juego Terminado' }
        format.js
        format.json { head :no_content }
      else
        format.html { redirect_to @game, notice: 'Invalid move.' }
        format.js
      end
    end
  end
  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper

  require 'net/http'
  #diccionario

  $words = {}

  File.open("public/wordsEn.txt", "r") do |file|
    file.each do |line|
      $words[line.strip] = true
    end
  end 

	  #Haciendo el calculo del puntaje del juego, todos retornan verdaderos si pertenecen al puntaje
  def double_letter(y,x)
  	coordinate = [[0,3],[0,11],[2,6],[2,8],[3,0],[3,7],[3,14],[6,2],[6,6],[6,8],[6,12],[7,3],[7,11],[8,2],[8,6],[8,8],[8,12],[11,0],[11,7],[11,14],[12,6],[12,8],[14,3],[14,11]]
  	result = false
  	coordinate.each do |i,j|	
  		if i == y and j == x
  			result = true
  			break
  		else
  			result = false
  		end
  	end
  	result
  end

  def triple_word(y,x)
  	if [0,7,14].include? y and [0,7,14].include? x and !(x == y and x == 7)
  		true
  	else
  		false
  	end
  end

  def double_word(y,x)
  	coordinate = [[1,1],[2,2],[3,3],[4,4],[10,10],[11,11],[12,12],[13,13],[1,13],[2,12],[3,11],[4,10],[10,4],[11,3],[12,2],[13,1]]
  	result = false
  	coordinate.each do |i,j|	
  		if i == y and j == x
  			result = true
  			break
  		else
  			result = false
  		end
  	end
  	return result
  end 

  def triple_letter(y,x)
  	coordinate = [[1,5],[1,9],[5,1],[5,5],[5,9],[5,13],[9,1],[9,5],[9,9],[9,13],[13,5],[13,9]]
  	result = false
  	coordinate.each do |i,j|	
  		if i == y and j == x
  			result = true
  			break
  		else
  			result = false
  		end
  	end
  	return result
  end
  

  def get_letter_from_number(n)
    n=n+64
    n.chr
  end

  def points_for_letter(letter)
      l = letter.upcase.to_sym
      point_hash = {A: 1,
                   B: 3,
                   C: 3,
                   D: 2,
                   E: 1,
                   F: 4,
                   G: 2,
                   H: 4,
                   I: 1,
                   J: 8,
                   K: 5,
                   L: 1,
                   M: 3,
                   N: 1,
                   O: 1,
                   P: 3,
                   Q: 10,
                   R: 1,
                   S: 1,
                   T: 1,
                   U: 1,
                   V: 4,
                   W: 4,
                   X: 8,
                   Y: 4,
                   Z: 10}

      point_hash[l]
  end

  #esta función compara el diccionario con las palabras creadas
  def save_move(words_created)
    if words_created.size == 0
      return false
    end
    words_created.each do |word_c|
      word = word_c[0].downcase
      # original, sin la api
      #unless $words[word]
        #return false
      url = URI.parse('http://api.wordreference.com/1672a/json/enfr/' + word)
      req = Net::HTTP::Get.new(url.path)
      res = Net::HTTP.start(url.host, url.port){|http|
      http.request(req)
      }
      parsed_json = ActiveSupport::JSON.decode(res.body)
      if !parsed_json ["Error"].nil?
        return false
      end      
    end  
     true
  end

  #words_created tiene la palabra creada y el puntaje de esa palabra
  def validate_words(m)
    words_created = []
    15.times do |i|
      15.times do |j|
        if !m[i][j][0].nil?
          if !m[i][j][1]
            word_right = right_word(m,i,j)
            if word_right[0].length > 1
              words_created.push(word_right)
            end  
          end  
          if !m[i][j][2]
            word_down = down_word(m,i,j)  
            if word_down[0].length > 1
              words_created.push(word_down)
            end  
          end  
        end 
      end 
    end
    return words_created   
  end

  def right_word(m,i,j)
    right = ""
    double_w = false
    triple_w = false
    score_word = 0
    j.upto(14) do |k|
      if !m[i][k][0].nil?
        #puts "4444444444444444444444444444444444444444444444444444444444444444444"
        #puts m[i][k][0]
        right << m[i][k][0]
        m[i][k][1] = true

        multiplier = 1
        if(get_cell_class(i,k) == "double_letter")
          multiplier = 2
        elsif (get_cell_class(i,k) == "triple_letter")
          multiplier = 3
        end
        score_word += multiplier * points_for_letter(m[i][k][0])
              
        if(get_cell_class(i,k) == "triple_word")
          triple_w = true
        elsif (get_cell_class(i,k) == "double_word")
          double_w = true
        end

      else
        if triple_w
          score_word *= 3
        elsif double_w
          score_word *= 2
        end
        return [right, score_word]
      end    
    end
    if triple_w
      score_word *= 3
    elsif double_w
      score_word *= 2
    end
    return [right, score_word]
  end
  
  def down_word(m,i,j)
    down = ""
    double_w = false
    triple_w = false
    score_word = 0
    i.upto(14) do |k|
      if !m[k][j][0].nil?
        #puts "4444444444444444444444444444444444444444444444444444444444444444444"
        #puts m[i][k][0]
        down << m[k][j][0]
        m[k][j][2] = true

        multiplier = 1
        if(get_cell_class(k,j) == "double_letter")
          multiplier = 2
        elsif (get_cell_class(k,j) == "triple_letter")
          multiplier = 3
        end
        score_word += multiplier * points_for_letter(m[k][j][0])
              
        if(get_cell_class(k,j) == "triple_word")
          triple_w = true
        elsif (get_cell_class(k,j) == "double_word")
          double_w = true
        end

      else
        if triple_w
          score_word *= 3
        elsif double_w
          score_word *= 2
        end
        return [down, score_word]
      end
    end
    if triple_w
      score_word *= 3
    elsif double_w
      score_word *= 2
    end
    return [down, score_word]
  end

  def get_cell_class(i,j)

    if triple_word(i,j)
      return 'triple_word'
    elsif double_word(i,j)
      return 'double_word'

    elsif double_letter(i,j)
      return 'double_letter'
    elsif triple_letter(i,j)
      return 'triple_letter'
    elsif i == j and i ==7
      return 'center_cell'
    else
      return 'normal_cell'
    end

  end

  # no se puede poner letras en horizontales Y verticales distintas, sólo una variable puede ser distinta
  #validación de todas las letras en horizontal o vertical
  def move_accepted(m, moves)

    return false if moves.empty?
    x_first = moves.first.coordinate.split(",")[0].to_i
    y_first = moves.first.coordinate.split(",")[1].to_i
    horiz = false
    vertical = false

    ##Aqui falta el IF para que el mapa comience en el centro;
    #if m[7][7].nil?

    #iterar sobre moves para ver si alguno esta en el medio

    #si ya existe la primera jugada, habria que verificar que alguna letra de moves al lado de una letra del mapa
    #else

    # iterar sobre cada moves y revisar sus casillas cercanas
    # ojo que si es un borde y se accede como m[x_first + 1 ][y_first][0] el programa se cae

    #end


    if moves.size == 1
      #verifico si esta en algun borde antes de comprobar si hay alguna letra al lado
      #saque esta parte pq se tiene que hacer mas arriba

      #if m[x_first + 1].nil? || m[x_first -1].nil? || m[x_first][y_first + 1].nil? || m[x_first][y_first -1].nil?
      #  return false
      #end
      #
      #if m[x_first + 1 ][y_first][0] == nil and m[x_first -1 ][y_first][0] == nil and m[x_first][y_first + 1][0] == nil and m[x_first][y_first -1][0] == nil
      #  return false
      moves.each do |x|
        pos_x = x.coordinate.split(",")[0].to_i
        pos_y = x.coordinate.split(",")[1].to_i
        m[pos_x][pos_y][0] = x.letter
      end
      return true
    else  
      moves.each do |x|
        pos_x = x.coordinate.split(",")[0].to_i
        if pos_x != x_first
          horiz = true
        end  
        pos_y = x.coordinate.split(",")[1].to_i
        if pos_y != y_first
          vertical = true
        end
        
        if vertical and horiz
           return false
        else
          m[pos_x][pos_y][0] = x.letter
        end
      end
    end
    true
  end

end

app/views/games/_board.erb
                  <%board = @game.build_board %>
<div id="boardContainer" data-id="<%= @game.id %>" data-updated-at="<%= @game.updated_at.to_i%>">
  <% for i in 0..14 %>
      <div class="boardRow">
        <% for j in 0..14 %>
            <% special_cell = get_cell_class(i,j) %>
            <% if(board[i][j][0]) %>
                <div id="cell_<%=i%>_<%=j%>" class ="boardCell  ui-widget-content <%= special_cell%>" posx="<%=i %>" posy="<%=j %>">
                    <div id="fixed_tile_<%= i %>_<%= j %>" class ="fixed_tile ui-widget-content">
                      <span class="letter_<%=board[i][j][0]%>"></span>
                      <span class="score_<%=points_for_letter(board[i][j][0]) %>"></span>
                    </div>
                </div>
            <% else %>
                <div id="cell_<%=i%>_<%=j%>" class ="boardCell droppable ui-widget-content <%= special_cell%>" posx="<%=i %>" posy="<%=j %>">
                </div>
            <% end %>





        <% end %>
      </div>
  <% end %>
</div>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <% players_array = []%>
    <% players_array = Player.where("id != ?", @player).map {|p|  [p.name,p.mail]}%>
    <% players_array.unshift(['',''])%>
    <p>Invita al menos a 1 jugador</p>
    <div class="field">
      Email jugador 1:<%= select_tag(:user1, options_for_select(players_array))%>
    </div>
    <div class="field">
      Email jugador 2:<%= select_tag(:user2, options_for_select(players_array))%>
    </div>
    <div class="field">

      Email jugador 3:<%= select_tag(:user3, options_for_select(players_array))%>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/_player_tiles.erb
<div id="caseContainer">
  <% for j in 1..7 %>
      <div id="case<%= j %>" class="case droppable ui.widget-content">
        <div id="tile<%= j %>" class ="tile <%= 'draggable' if true%> ui-widget-content">
          <% letter = get_letter_from_number(@player_state.get_state_letter(j).to_i) %>
          <span class="letter_<%=letter%>"></span>
          <span class="score_<%=points_for_letter(letter) %>"></span>
        </div>
      </div>
  <% end %>
</div>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', @player %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <tr>
    <th>Language</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= game.language_id %></td>
    <td><%= link_to 'Show', game %></td>
    <td><%= link_to 'Edit', edit_game_path(game) %></td>
    <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', @player %>

app/views/games/show.html.erb
<%  content_for(:head) { javascript_include_tag 'games'  } %>

<div id= "container">

    <div id = "center" class = "column">

        <%= render 'board' %>

        <%= form_tag game_path(@game), :method=>'put' ,remote:true,  id: 'play_form' do%>
            <% for i in 1..7 %>
                <%=hidden_field_tag "tile_#{i}", '',{ :class=> "tile-input" } %>
                <%=hidden_field_tag "tile_#{i}_x" , '',{ :class=> "tile-input" } %>
                <%=hidden_field_tag "tile_#{i}_y", '',{ :class=> "tile-input" }  %>
            <% end %>
            <%= submit_tag 'Play' , :onclick => "setHiddenMoveForm()",class:'btn', id:"buttonplay" %>
        <% end %>

      <%= form_tag end_game_path(@game), method:'put' do %>
          <% submit_tag 'Surrender' ,class:'btn btn-danger',id:'buttonsurrender'%>
          <% end %>
        <p>
         <%= render 'player_tiles' %>
        </p>
        	<!--  -->
    </div>

    <div id = "left" class = "column">
        <p> </p>
    </div>  

    <div id = "right" class = "column">
        <p>
            <b>Language: English <%= @game.language_id %></b>
        </p>
        <p>
            <b>Current turn: <span id="currentTurn"><%= @next_turn%></span></b>   
        </p>
        <hr>    
        <%@game_status.each do |g| %>
            <p> 
                <b>Jugador: <%= g[0] %></b>
            </p>   
            <p>
                <b>Turn number: </b>
                    <b id="player_turn_<%=g[3] %>">
                <%if g[1] == @next_turn %>
                     YOUR TURN
                <% else %>                  
                    <%= g[1] %>
                <%end %>
                    </b>
            </p>
            <p>
                <b>Score: <span id="score_<%= g[3] %>"><%= g[2] %></span> </b>
            </p>
            <hr>
        <% end %>
    </div>          
</div>

<div id = "footer">    
    <%= link_to 'Edit', edit_game_path(@game) %> |
    <%= link_to 'Back', player_path(current_player) %>
</div>

app/views/games/show.js.erb
<% data= []%>
<% @states.each do |s|  %>
<% if @game.next_turn == s.turn%>
<% turn = "YOUR TURN"%>
<% else turn = s.turn%>
<% end %>

<% data << [s.player_id,s.score,turn] %>
<%end %>

updateTable(<%= @game.build_board_for_ajax.to_json.html_safe %>);
updatePlayerTiles(<%= @player_state.get_state_letters.to_json.html_safe%>) ;
updateInfo(<%= data.to_json.html_safe%>,<%=@game.next_turn %>);
updateBoard(<%=@game.updated_at.to_i  %>);

app/views/games/update.js.erb
<% data= []%>
<% @states.each do |s|  %>
<% if @game.next_turn == s.turn%>
<% turn = "YOUR TURN"%>
<% else turn = s.turn%>
<% end %>

<% data << [s.player_id,s.score,turn] %>
<%end %>

updateTable(<%= @game.build_board_for_ajax.to_json.html_safe %>);
updatePlayerTiles(<%= @player_state.get_state_letters.to_json.html_safe%>) ;
updateInfo(<%= data.to_json.html_safe%>,<%=@game.next_turn %>);
updateBoard(<%=@game.updated_at.to_i  %>);