config/routes.rb
Scrabble::Application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"

  get "log_in" => "sessions#new", :as => "log_in"

  get "sign_up" => "players#new", :as => "sign_up"

  root :to => "players#new"

  controller :api, defaults: {format:'json'} do
    get 'api/ranking' =>'api#ranking'
    get 'api/check_word/:word' => 'api#check_word'
    get 'api/compare' => 'api#compare'
  end

  resources :states

  resources :games
  put 'games/end/:id' => 'games#end' , as: 'end_game'

  resources :players do
    collection do
      get :ranking
    end    
  end

  resources :moves

  resources :sessions

end

app/models/player.rb
class Player < ActiveRecord::Base

  attr_accessible :mail, :name, :password
  
  attr_accessor :password

  before_save :encrypt_password

  validates_presence_of :password, :on => :create
  validates_presence_of :mail
  validates_presence_of :name
  validates_uniqueness_of :mail

  has_many :states
  has_many :games, :through => :states
  has_many :moves

  def self.authenticate(mail, password)
    player = find_by_mail(mail)
    if player && player.password_hash == BCrypt::Engine.hash_secret(password, player.password_salt)
      player
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def count_moves(game_id)
    count = self.moves.where(:game_id => game_id).maximum(:move_number)
    count == nil ?  0 :  count
  end

  def max_score
    if self.states.size > 0
      self.states.maximum("score")
    else
      0
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  # GET /players
  # GET /players.json
  def index
    @players = Player.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
    end
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @player = Player.find(params[:id])
    
    #player_states = @player.states
    #@games_player = []

    #player_states.each do |s|
     # state_player = State.find(s)
      #games_player recibe los ids de los games que el jugador participa y está activo
      #if state_player.player_state = "active"
       # names_player = []
        #game_active = Game.find(state_player.game_id)
        # quiero encontrar los jugadores que participan del juego
        #game_active.states.each do |h|
         # player_participant = State.find(h)
          #player_participant2 = Player.find(player_participant.player_id)
          #names_player.push(player_participant2.name)
        #end  
       #@games_player.push([state_player.game_id, game_active.created_at, names_player])
      #end 
    #end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/new
  # GET /players/new.json
  def new
    
    if current_player
      redirect_to player_path (current_player)
    else
      @player = Player.new
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @player }
      end
    end
  end

  # GET /players/1/edit
  def edit
    @player = Player.find(params[:id])
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(params[:player])

    respond_to do |format|
      if @player.save
          session[:player_id] = @player.id
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render json: @player, status: :created, location: @player }
      else
        format.html { render action: "new" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /players/1
  # PUT /players/1.json
  def update
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player = Player.find(params[:id])
    reset_session
    @player.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  def ranking
    @players = Player.all.sort_by {|player| player.max_score}.reverse
    respond_to do |format|
      format.html
      format.json
    end
  end  
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :mail %><br />
    <%= f.email_field :mail %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/_game.html.erb
     <% if @player.states.where(game_id: game).first.player_state == 'active'%>
<li>
<%=  link_to "Play", game_path(game)%>
    <span>Against:
        <% game.players.each do |p| %>
            <%= p.name if @player != p%>
        <%end%>
    </span>
</li>
             <% end%>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Back', @player %>

app/views/players/index.html.erb
<h1>Listing players</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Mail</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @players.each do |player| %>
  <tr>
    <td><%= player.name %></td>
    <td><%= player.mail %></td>
    <td><%= player.password %></td>
    <td><%= link_to 'Show', player %></td>
    <td><%= link_to 'Edit', edit_player_path(player) %></td>
    <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<div id="sign_log">

  <h1 id="sign_log_title">Sign Up</h1>

  <%= form_for @player do |f| %>
    <% if @player.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @player.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :mail %><br />
      <%= f.email_field :mail %>
    </p>
    <p>
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </p>

    <p class="button"><%= f.submit %></p>
  <% end %>

</div>

app/views/players/ranking.html.erb
<div id = "ranking">

<h1>Ranking</h1>

<table class= "ranking_tabla">
  <tr>
    <th>Name</th>
    <th>Mail</th>
    <th>Score</th>
  </tr>

<% @players.each do |player| %>
  <tr>
    <td><%= player.name %></td>
    <td><%= player.mail %></td>
    <td><%= player.max_score %></td>
  </tr>
<% end %>
</table>

</div>

app/views/players/show.html.erb
<p>
  <b>Mail:</b>
  <%= @player.mail %>
</p>
      <ol>
<%=	 render :partial => 'game', collection: @player.games, :as => :game %>
      </ol>
<p><%= link_to 'New game', new_game_path %></p>
<%= link_to 'Edit Profile', edit_player_path(@player) %> |
<%= link_to "Delete user", player_path, :method => :delete %>