config/routes.rb
Scrabble::Application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"

  get "log_in" => "sessions#new", :as => "log_in"

  get "sign_up" => "players#new", :as => "sign_up"

  root :to => "players#new"

  controller :api, defaults: {format:'json'} do
    get 'api/ranking' =>'api#ranking'
    get 'api/check_word/:word' => 'api#check_word'
    get 'api/compare' => 'api#compare'
  end

  resources :states

  resources :games
  put 'games/end/:id' => 'games#end' , as: 'end_game'

  resources :players do
    collection do
      get :ranking
    end    
  end

  resources :moves

  resources :sessions

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scrabble</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= yield(:head) %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id = "all">

  <div id="player_nav">
    <%=link_to image_tag("scrabble.png"), url_for(sign_up_path) %>
    <div id = "status">
      <% if current_player %>
        Logged in as <%= link_to current_player.name, player_path(current_player) %>.
        <%= link_to "Log out", log_out_path %>
      <% else %>
        <%= link_to "Sign up", sign_up_path %> or
        <%= link_to "log in", log_in_path %>
      <% end %>
      <br> <%= link_to "Ranking", ranking_players_path %></br>
    </div>
      
  </div>

  <div id ="noticeBig">
    <div id = "notice">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
     </div> 
  </div>  

  <div id="yield">
    <%= yield %>
  </div>

</div>

</body>
</html>